import { test, expect } from "@playwright/test";
import { createHmac } from "node:crypto";
function totp(secret: string) {
  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
  let bits = "";
  for (const c of secret)
    bits += alphabet.indexOf(c).toString(2).padStart(5, "0");
  const key = Buffer.from(bits.match(/.{8}/g)!.map((b) => parseInt(b, 2)));
  const counter = Buffer.alloc(8);
  counter.writeBigUInt64BE(BigInt(Math.floor(Date.now() / 30000)));
  const hash = createHmac("sha1", key).update(counter).digest();
  const offset = hash[19] & 15;
  return ((hash.readUInt32BE(offset) & 0x7fffffff) % 1000000)
    .toString()
    .padStart(6, "0");
}
for (const role of ["admin", "recruiter", "client"]) {
  test(`${role} signs in and uses the shared search`, async ({ page }) => {
    await page.goto("/login");
    await page.getByLabel("Email address").fill(`${role}@example.com`);
    await page
      .getByLabel("Password", { exact: true })
      .fill("E2E-Only-Password!");
    await page.getByRole("button", { name: "Sign in", exact: true }).click();
    if (role === "admin") {
      // Each browser uses recovery codes generated by the first enrolment.
      const setup = page.getByRole("button", { name: "Generate setup key" });
      await expect(
        page.getByRole("heading", {
          name: /authenticator|administrator account/,
        }),
      ).toBeVisible();
      if (await setup.isVisible()) {
        await setup.click();
        const secret = await page.locator("code").innerText();
        await page
          .getByLabel("Authenticator or recovery code")
          .fill(totp(secret));
        await page.getByRole("button", { name: "Verify code" }).click();
        await expect(
          page.getByRole("button", { name: "I have saved my recovery codes" }),
        ).toBeVisible();
        const { writeFileSync } = await import("node:fs");
        writeFileSync(
          "/tmp/searchroom-e2e-recovery.json",
          JSON.stringify((await page.locator("pre").innerText()).split("\n")),
        );
        await page
          .getByRole("button", { name: "I have saved my recovery codes" })
          .click();
      } else {
        const { readFileSync, writeFileSync } = await import("node:fs");
        const codes = JSON.parse(
          readFileSync("/tmp/searchroom-e2e-recovery.json", "utf8"),
        );
        const code = codes.shift();
        writeFileSync(
          "/tmp/searchroom-e2e-recovery.json",
          JSON.stringify(codes),
        );
        await page.getByLabel("Authenticator or recovery code").fill(code);
        await page.getByRole("button", { name: "Verify code" }).click();
      }
    }
    await expect(
      page.getByRole("heading", { name: "Search workspace." }),
    ).toBeVisible();
    expect(
      await page.evaluate(() => localStorage.getItem("searchroom.tokens")),
    ).toBeNull();
    await page.getByRole("heading", { name: "Head of Product" }).click();
    await page.getByRole("link", { name: "Candidates", exact: true }).click();
    await expect(
      page.getByRole("heading", { name: "Olivia Bennett" }),
    ).toBeVisible();
    if (role === "client")
      await expect(
        page.getByRole("button", { name: "Add candidate" }),
      ).toHaveCount(0);
    await page.getByRole("link", { name: /Messages/ }).click();
    await page.getByLabel("Your message").fill(`Browser smoke ${role}`);
    await page.getByRole("button", { name: "Send message" }).click();
    await expect(
      page.getByText(`Browser smoke ${role}`, { exact: true }).last(),
    ).toBeVisible();
    await page.reload();
    await expect(
      page.getByText(`Browser smoke ${role}`, { exact: true }).last(),
    ).toBeVisible();
    await page.getByRole("link", { name: "Timeline", exact: true }).click();
    await expect(
      page.getByText("Confirm interview availability"),
    ).toBeVisible();
  });
}
