"""Production sessions account lifecycle and resource bounds"""
from alembic import op
import sqlalchemy as sa

revision = 'readiness_20260913'
down_revision = '73bd82fc50b5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_agency_id'), 'audit_events', ['agency_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_table('email_actions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_email_actions_email'), 'email_actions', ['email'], unique=False)
    op.create_index(op.f('ix_email_actions_expires_at'), 'email_actions', ['expires_at'], unique=False)
    op.create_table('mail_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.String(length=254), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_outbox_next_attempt_at'), 'mail_outbox', ['next_attempt_at'], unique=False)
    op.create_table('rate_buckets',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_rate_buckets_expires_at'), 'rate_buckets', ['expires_at'], unique=False)
    op.create_table('submissions',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_submissions_created_at'), 'submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_submissions_project_id'), 'submissions', ['project_id'], unique=False)
    op.create_table('web_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idle_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mfa_complete', sa.Boolean(), nullable=False),
    sa.Column('delivered', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_web_sessions_expires_at'), 'web_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_web_sessions_user_id'), 'web_sessions', ['user_id'], unique=False)
    op.add_column('agencies', sa.Column('retention_days', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.create_index('ix_candidates_project_id_id', 'candidates', ['project_id', 'id'], unique=False)
    op.create_index('ix_comments_post_id_id', 'comments', ['post_id', 'id'], unique=False)
    op.create_index('ix_documents_project_id_id', 'documents', ['project_id', 'id'], unique=False)
    op.create_index('ix_feedback_candidate_id_id', 'feedback', ['candidate_id', 'id'], unique=False)
    op.create_index('ix_invitations_agency_id_id', 'invitations', ['agency_id', 'id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_index('ix_messages_project_id_id', 'messages', ['project_id', 'id'], unique=False)
    op.add_column('milestones', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.create_index('ix_milestones_project_date_id', 'milestones', ['project_id', 'target_date', 'id'], unique=False)
    op.create_index('ix_posts_project_id_id', 'posts', ['project_id', 'id'], unique=False)
    op.add_column('projects', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('projects', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('mfa_secret', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('mfa_last_step', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('recovery_hashes', sa.JSON(), server_default='[]', nullable=False))
    op.execute("UPDATE auth_sessions SET revoked = true")

def downgrade():
    raise RuntimeError('Readiness migration is forward-only. Restore an isolated backup for disaster recovery; do not reactivate the legacy authentication application.')
